### ISSUE TITLE
Building help

### ISSUE THREAD

**Issue by erm3nda** [nagua/Sailfish-Taskwarrior-GUI#56]
I did expect little guidance on the readme.md to build up that, or at least a Makefile for it.
Could anyone point me to what is needed to build that?

**Comment by nagua** [comment]
Hey, this is a standard Sailfish OS application. You just need to install the Sailfish SDK, start Qt Creator load the project and compile it. But you need to have a Sailfish OS smartphone/tablet to make use of the application. But I will add a howto for that in the readme. I will keep the issue open until this is done.

**Comment by erm3nda** [comment]
Sorry. First time i hear about Sailfish, my fault.

I didn't read anything like "only for " Sailfish OS application so i wondered it where Linux wide.
I've looked at Tools section of Taskwarrior and finally got some other tools, like ptask and the web interface provided by inthe.am

Thank you.
